name: constructo
description: Framework for object models .
version: 0.0.1
homepage: https://github.com/reimashi/constructo
author: Aitor González Fernández <reimashi@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:

dev_dependencies:
  test: ^0.12.0

web:
  compiler:
    debug: dartdevc
    release: dart2js